name: Check for RC

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-for-rc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: 'rancher/ecm-distro-tools'
          ref: 'add-verify-ga-command'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Specify your required version
          check-latest: true

      - name: Build Go binary
        run: go build -o release ./cmd/release/main.go

      - name: Run release verify
        run: ./release verify ga
